Add three new functions to common.py
robbrad/UKBinCollectionData pull request #1000
Opened 2024-11-12 22:57 UTC by dp247

A few more functions for common.py - these may be useful for calendars where we know the collection day, but have no way of scraping data and have to use our own functions to generate them.

## is_weekend()
A counterpart to is_holiday(), provides an easy way of finding out if a date is on a Saturday/Sunday.

## is_working_day()
I'm defining 'working day' as any day Monday to Friday that is not a holiday. This function is a wrapper for both is_holiday and is_weekend - if one is True for the given date, false is returned.

## get_next_working_day()
Could be useful when used with the above - returns the next working day according to the criteria above

2024-11-12 22:57 UTC, dp247 commented
Feel free to ignore the revert, I wasn't looking at the tickboxes in Pycharm LOL

2024-11-12 22:58 UTC, dp247 commented
Also happy one thousandth issue!

2024-11-13 12:20 UTC, dannya commented on uk_bin_collection/uk_bin_collection/common.py
> +    return True if date_to_check.date().weekday() >= 5 else False
couldn't this just be:

`return date_to_check.date().weekday() >= 5`

?

2024-11-13 12:25 UTC, dp247 commented on uk_bin_collection/uk_bin_collection/common.py
> +    return True if date_to_check.date().weekday() >= 5 else False
For sure.

2024-11-14 23:49 UTC, robbrad requested changes
Looks to be some extra tabs added to the common functions @dp247 ? Do the unit tests work?

Can you add the coverage for the new tests?

2024-11-20 22:16 UTC, dp247 commented
> Looks to be some extra tabs added to the common functions @dp247 ? Do the unit tests work?
> 
> Can you add the coverage for the new tests?

Yes, I'll get this sorted when I've returned from my travels

2024-12-14 07:35 UTC, robbrad requested changes
I cloned this and it seams the common unit tests are no longer executing - I can review further on Sunday night

2024-12-17 08:11 UTC, robbrad approved these changes

2024-12-17 08:11 UTC, merged