Home Assistant custom component
robbrad/UKBinCollectionData pull request #324
Opened 2023-09-09 06:44 UTC by robbrad

2023-09-10 17:18 UTC, OliverCullimore requested changes

2023-09-10 17:18 UTC, OliverCullimore commented on custom_components/uk_bin_collection/__init__.py
> +    # coordinator = UKBinCollectionDataUpdateCoordinator(hass, entry.data)
Could probably remove this commented line?

2023-09-10 17:18 UTC, OliverCullimore commented on uk_bin_collection/uk_bin_collection/councils/CheshireEastCouncil.py
Did we mean to be updating a council as part of merging this?

2023-09-10 17:18 UTC, OliverCullimore commented on custom_components/uk_bin_collection/__init__.py
> +    # hass.data[DOMAIN][entry.entry_id] = coordinator
Could probably remove this commented line too?

2023-09-10 17:18 UTC, OliverCullimore commented on custom_components/uk_bin_collection/config_flow.py
> +        url = "https://raw.githubusercontent.com/robbrad/UKBinCollectionData/master/uk_bin_collection/tests/input.json"
We may need to bundle this file as part of the Python library build process to ensure we use a copy that matches the library's capabilities so the component doesn't try to offer Councils that aren't supported in the version that's currently installed?

2023-09-15 16:44 UTC, OliverCullimore approved these changes

2023-09-15 16:50 UTC, merged

2023-09-15 18:33 UTC, robbrad commented
Thanks @OliverCullimore !!