Epping Forest District Council
robbrad/UKBinCollectionData pull request #629
Opened 2024-03-03 00:45 UTC by raddzz

Adding support for Epping Forest District Council should close #554

2024-03-13 10:26 UTC, dp247 requested changes
Looks good - just need the indentation fixing on the feature file

2024-03-13 10:26 UTC, dp247 commented on uk_bin_collection/tests/features/validate_council_outputs.feature
Lines 200-204 need their indentation moving back 😉

2024-04-27 15:44 UTC, robbrad commented on uk_bin_collection/tests/features/validate_council_outputs.feature
@raddzz ^

2024-05-27 07:30 UTC, robbrad commented
added to PR https://github.com/robbrad/UKBinCollectionData/pull/739

2024-05-27 07:30 UTC, closed without merging